# Generated by Django 2.2.1 on 2019-06-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaItemQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_alternativa', models.IntegerField(choices=[(1, 'Única Escolha')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlternativaQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_alternativa', models.IntegerField(choices=[(1, 'Única Escolha'), (2, 'Texto')], default=1)),
                ('resposta', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('requerida', models.BooleanField(default=True)),
                ('tipo_questao', models.IntegerField(choices=[(1, 'Texto Livre'), (2, 'Única Escolha'), (3, 'Múltipla Escolha'), (4, 'Avaliação')])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosQuestionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('submetido', models.BooleanField()),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_questionarios', to='questionarios.Questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_questionarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'questionario')},
            },
        ),
        migrations.CreateModel(
            name='QuestionariosQuestoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('resposta', models.TextField(blank=True)),
                ('alternativa_item_questao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes_alternativa_item_questao', to='questionarios.AlternativaItemQuestao')),
                ('alternativa_selecionada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes_alternativa_selecionada', to='questionarios.AlternativaQuestao')),
                ('alternativas_selecionadas', models.ManyToManyField(blank=True, related_name='questionarios_questoes_alternativas_selecionadas', to='questionarios.AlternativaQuestao')),
                ('item_questao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes_item_questao', to='questionarios.ItemQuestao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes', to='questionarios.Questao')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes', to='questionarios.Questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios_questoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='questionario',
            name='respostas',
            field=models.ManyToManyField(blank=True, related_name='questionarios', through='questionarios.QuestionariosQuestoes', to='questionarios.Questao'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='questionarios', through='questionarios.UsuariosQuestionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='questionarios.Questionario'),
        ),
        migrations.AddField(
            model_name='itemquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_questao', to='questionarios.Questao'),
        ),
        migrations.AddField(
            model_name='alternativaquestao',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questionarios.Questao'),
        ),
        migrations.AddField(
            model_name='alternativaitemquestao',
            name='item_questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questionarios.ItemQuestao'),
        ),
    ]
