# Generated by Django 2.2.1 on 2019-06-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemquestao',
            old_name='descricao',
            new_name='titulo',
        ),
    ]
