# Generated by Django 2.2.1 on 2019-05-30 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respostaquestao',
            unique_together={('questao', 'usuario')},
        ),
    ]
