# Generated by Django 2.2.1 on 2019-05-31 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativaquestao',
            name='alternativa_selecionada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativa_questao_alternativa_selecionada', to='questionarios.AlternativaQuestao'),
        ),
        migrations.AddField(
            model_name='alternativaquestao',
            name='alternativas_selecionadas',
            field=models.ManyToManyField(blank=True, related_name='alternativa_questao_alternativas_selecionadas', to='questionarios.AlternativaQuestao'),
        ),
        migrations.AlterField(
            model_name='alternativaquestao',
            name='tipo_alternativa',
            field=models.IntegerField(choices=[(1, 'Texto'), (2, 'Única Escolha'), (3, 'Múltipla Escolha')], default=2),
        ),
    ]
