# Generated by Django 2.2.1 on 2019-06-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_auto_20190605_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionariosquestoes',
            options={},
        ),
    ]
